module.exports = {
  API_URL: 'https://api.guildwars2.com/v2/',
  ACHIEVEMENT_ENDPOINT: 'achievements/',
  ACHIEVEMENT_CATEGORY_ENDPOINT: 'achievements/categories/',
  FRACTAL_DAILY_CATEGORY: 88,

  FRACTALS: [ // Should come from some API endpoint
      { "scale": 1, "map": "Urban Battleground Fractal", "agony": 0 },
      { "scale": 2, "map": "Swampland Fractal", "info": "Bloomhunger", "agony": 0 },
      { "scale": 3, "map": "Aquatic Ruins Fractal", "info": "Dark Path", "agony": 0 },
      { "scale": 4, "map": "Uncategorized Fractal", "agony": 0 },
      { "scale": 5, "map": "Snowblind Fractal", "agony": 0 },
      { "scale": 6, "map": "Volcanic Fractal", "agony": 0 },
      { "scale": 7, "map": "Cliffside Fractal", "agony": 0 },
      { "scale": 8, "map": "Underground Facility Fractal", "info": "Guns", "agony": 0 },
      { "scale": 9, "map": "Molten Furnace Fractal", "agony": 0 },
      { "scale": 10, "map": "Molten Boss Fractal", "agony": 0 },
      { "scale": 11, "map": "Urban Battleground Fractal", "agony": 0 },
      { "scale": 12, "map": "Uncategorized Fractal", "agony": 0 },
      { "scale": 13, "map": "Cliffside Fractal", "agony": 0 },
      { "scale": 14, "map": "Aetherblade Fractal", "agony": 0 },
      { "scale": 15, "map": "Thaumanova Reactor Fractal", "agony": 0 },
      { "scale": 16, "map": "Snowblind Fractal", "agony": 0 },
      { "scale": 17, "map": "Underground Facility Fractal", "info": "Bombs", "agony": 0 },
      { "scale": 18, "map": "Aquatic Ruins Fractal", "info": "Dolphin Path", "agony": 0 },
      { "scale": 19, "map": "Volcanic Fractal", "agony": 0 },
      { "scale": 20, "map": "Solid Ocean Fractal", "agony": 8 },
      { "scale": 21, "map": "Swampland Fractal", "info": "Mossman", "agony": 10 },
      { "scale": 22, "map": "Cliffside Fractal", "agony": 11 },
      { "scale": 23, "map": "Molten Furnace Fractal", "agony": 13 },
      { "scale": 24, "map": "Aetherblade Fractal", "agony": 15 },
      { "scale": 25, "map": "Captain Mai Trin Boss Fractal", "agony": 17 },
      { "scale": 26, "map": "Aquatic Ruins Fractal", "info": "Dolphin Path", "agony": 19 },
      { "scale": 27, "map": "Snowblind Fractal", "agony": 20 },
      { "scale": 28, "map": "Volcanic Fractal", "agony": 22 },
      { "scale": 29, "map": "Underground Facility Fractal", "info": "Bombs", "agony": 24 },
      { "scale": 30, "map": "Solid Ocean Fractal", "agony": 26 },
      { "scale": 31, "map": "Urban Battleground Fractal", "agony": 27, "mistlock_instability": ["Boon Fumbler"] },
      { "scale": 32, "map": "Swampland Fractal", "info": "Bloomhunger", "agony": 29, "mistlock_instability": ["Boon Fumbler"] },
      { "scale": 33, "map": "Cliffside Fractal", "agony": 31, "mistlock_instability": ["Boon Fumbler"] },
      { "scale": 34, "map": "Thaumanova Reactor Fractal", "agony": 33, "mistlock_instability": ["Boon Fumbler"] },
      { "scale": 35, "map": "Solid Ocean Fractal", "agony": 35, "mistlock_instability": ["Boon Fumbler"] },
      { "scale": 36, "map": "Uncategorized Fractal", "agony": 36, "mistlock_instability": ["Boon Fumbler"] },
      { "scale": 37, "map": "Snowblind Fractal", "agony": 38, "mistlock_instability": ["Boon Fumbler"] },
      { "scale": 38, "map": "Underground Facility Fractal", "info": "Guns", "agony": 40, "mistlock_instability": ["Boon Fumbler"] },
      { "scale": 39, "map": "Molten Furnace Fractal", "agony": 42, "mistlock_instability": ["Boon Fumbler"] },
      { "scale": 40, "map": "Molten Boss Fractal", "agony": 43, "mistlock_instability": ["Boon Fumbler"] },
      { "scale": 41, "map": "Swampland Fractal", "info": "Mossman", "agony": 45, "mistlock_instability": ["No Pain, No Gain"] },
      { "scale": 42, "map": "Aquatic Ruins Fractal", "info": "Dolphin Path", "agony": 47, "mistlock_instability": ["No Pain, No Gain"] },
      { "scale": 43, "map": "Underground Facility Fractal", "info": "Bombs", "agony": 49, "mistlock_instability": ["No Pain, No Gain"] },
      { "scale": 44, "map": "Uncategorized Fractal", "agony": 50, "mistlock_instability": ["No Pain, No Gain"] },
      { "scale": 45, "map": "Solid Ocean Fractal", "agony": 52, "mistlock_instability": ["No Pain, No Gain"] },
      { "scale": 46, "map": "Volcanic Fractal", "agony": 54, "mistlock_instability": ["No Pain, No Gain"] },
      { "scale": 47, "map": "Cliffside Fractal", "agony": 56, "mistlock_instability": ["No Pain, No Gain"] },
      { "scale": 48, "map": "Thaumanova Reactor Fractal", "agony": 57, "mistlock_instability": ["No Pain, No Gain"] },
      { "scale": 49, "map": "Aetherblade Fractal", "agony": 59, "mistlock_instability": ["No Pain, No Gain"] },
      { "scale": 50, "map": "Captain Mai Trin Boss Fractal", "agony": 61, "mistlock_instability": ["No Pain, No Gain"] },
      { "scale": 51, "map": "Snowblind Fractal", "agony": 63, "mistlock_instability": ["Last Laugh"] },
      { "scale": 52, "map": "Volcanic Fractal", "agony": 65, "mistlock_instability": ["Last Laugh"] },
      { "scale": 53, "map": "Underground Facility Fractal", "info": "Bombs", "agony": 67, "mistlock_instability": ["Last Laugh"] },
      { "scale": 54, "map": "Aetherblade Fractal", "agony": 69, "mistlock_instability": ["Last Laugh"] },
      { "scale": 55, "map": "Thaumanova Reactor Fractal", "agony": 70, "mistlock_instability": ["Last Laugh"] },
      { "scale": 56, "map": "Swampland Fractal", "info": "Bloomhunger", "agony": 72, "mistlock_instability": ["Last Laugh"] },
      { "scale": 57, "map": "Urban Battleground Fractal", "agony": 74, "mistlock_instability": ["Last Laugh"] },
      { "scale": 58, "map": "Molten Furnace Fractal", "agony": 75, "mistlock_instability": ["Last Laugh"] },
      { "scale": 59, "map": "Cliffside Fractal", "agony": 77, "mistlock_instability": ["Last Laugh"] },
      { "scale": 60, "map": "Solid Ocean Fractal", "agony": 79, "mistlock_instability": ["Last Laugh"] },
      { "scale": 61, "map": "Aquatic Ruins Fractal", "info": "Dark Path", "agony": 81, "mistlock_instability": ["Sluggish", "Afflicted"] },
      { "scale": 62, "map": "Uncategorized Fractal", "agony": 83, "mistlock_instability": ["Sluggish", "Afflicted"] },
      { "scale": 63, "map": "Volcanic Fractal", "agony": 85, "mistlock_instability": ["Sluggish", "Afflicted"] },
      { "scale": 64, "map": "Thaumanova Reactor Fractal", "agony": 86, "mistlock_instability": ["Sluggish", "Afflicted"] },
      { "scale": 65, "map": "Aetherblade Fractal", "agony": 88, "mistlock_instability": ["Sluggish", "Afflicted"] },
      { "scale": 66, "map": "Urban Battleground Fractal", "agony": 89, "mistlock_instability": ["Sluggish", "Afflicted"] },
      { "scale": 67, "map": "Swampland Fractal", "info": "Mossman", "agony": 91, "mistlock_instability": ["Sluggish", "Afflicted"] },
      { "scale": 68, "map": "Underground Facility Fractal", "info": "Guns", "agony": 93, "mistlock_instability": ["Sluggish", "Afflicted"] },
      { "scale": 69, "map": "Cliffside Fractal", "agony": 95, "mistlock_instability": ["Sluggish", "Afflicted"] },
      { "scale": 70, "map": "Solid Ocean Fractal", "agony": 97, "mistlock_instability": ["Sluggish", "Afflicted"] },
      { "scale": 71, "map": "Aetherblade Fractal",  "agony": 99, "mistlock_instability": ["Afflicted", "Boon Fumbler"] },
      { "scale": 72, "map": "Volcanic Fractal", "agony": 100, "mistlock_instability": ["Afflicted", "Boon Fumbler"] },
      { "scale": 73, "map": "Molten Furnace Fractal",   "agony": 102, "mistlock_instability": ["Afflicted", "Boon Fumbler"] },
      { "scale": 74, "map": "Snowblind Fractal", "agony": 104, "mistlock_instability": ["Afflicted", "Boon Fumbler"] },
      { "scale": 75, "map": "Aquatic Ruins Fractal", "info": "Dark Path", "agony": 106, "mistlock_instability": ["Afflicted", "Boon Fumbler"] },
      { "scale": 76, "map": "Underground Facility Fractal", "info": "Guns", "agony": 107, "mistlock_instability": ["Afflicted", "Boon Fumbler"] },
      { "scale": 77, "map": "Swampland Fractal", "info": "Mossman", "agony": 109, "mistlock_instability": ["Afflicted", "Boon Fumbler"] },
      { "scale": 78, "map": "Urban Battleground Fractal", "agony": 111, "mistlock_instability": ["Afflicted", "Boon Fumbler"] },
      { "scale": 79, "map": "Uncategorized Fractal", "agony": 113, "mistlock_instability": ["Afflicted", "Boon Fumbler"] },
      { "scale": 80, "map": "Molten Boss Fractal", "agony": 115, "mistlock_instability": ["Afflicted", "Boon Fumbler"] },
      { "scale": 81, "map": "Underground Facility Fractal", "info": "Bombs", "agony": 116, "mistlock_instability": ["Boon Fumbler", "Boon Thieves"] },
      { "scale": 82, "map": "Cliffside Fractal", "agony": 118, "mistlock_instability": ["Boon Fumbler", "Boon Thieves"] },
      { "scale": 83, "map": "Swampland Fractal", "info": "Mossman", "agony": 121, "mistlock_instability": ["Boon Fumbler", "Boon Thieves"] },
      { "scale": 84, "map": "Thaumanova Reactor Fractal", "agony": 122, "mistlock_instability": ["Boon Fumbler", "Boon Thieves"] },
      { "scale": 85, "map": "Urban Battleground Fractal", "agony": 124, "mistlock_instability": ["Boon Fumbler", "Boon Thieves"] },
      { "scale": 86, "map": "Snowblind Fractal", "agony": 125, "mistlock_instability": ["Boon Fumbler", "Boon Thieves"] },
      { "scale": 87, "map": "Volcanic Fractal", "agony": 127, "mistlock_instability": ["Boon Fumbler", "Boon Thieves"] },
      { "scale": 88, "map": "Aetherblade Fractal", "agony": 129, "mistlock_instability": ["Boon Fumbler", "Boon Thieves"] },
      { "scale": 89, "map": "Molten Furnace Fractal", "agony": 130, "mistlock_instability": ["Boon Fumbler", "Boon Thieves"] },
      { "scale": 90, "map": "Molten Boss Fractal", "agony": 132, "mistlock_instability": ["Boon Fumbler", "Boon Thieves"] },
      { "scale": 91, "map": "Uncategorized Fractal", "agony": 134, "mistlock_instability": ["Boon Thieves", "Social Awkwardness"] },
      { "scale": 92, "map": "Volcanic Fractal", "agony": 137, "mistlock_instability": ["Boon Thieves", "Social Awkwardness"] },
      { "scale": 93, "map": "Molten Furnace Fractal", "agony": 138, "mistlock_instability": ["Boon Thieves", "Social Awkwardness"] },
      { "scale": 94, "map": "Cliffside Fractal", "agony": 140, "mistlock_instability": ["Boon Thieves", "Social Awkwardness"] },
      { "scale": 95, "map": "Underground Facility Fractal", "info": "Bombs", "agony": 141, "mistlock_instability": ["Boon Thieves", "Social Awkwardness"] },
      { "scale": 96, "map": "Aetherblade Fractal", "agony": 143, "mistlock_instability": ["Boon Thieves", "Social Awkwardness"] },
      { "scale": 97, "map": "Thaumanova Reactor Fractal", "agony": 145, "mistlock_instability": ["Boon Thieves", "Social Awkwardness"] },
      { "scale": 98, "map": "Solid Ocean Fractal", "agony": 147, "mistlock_instability": ["Boon Thieves", "Social Awkwardness"] },
      { "scale": 99, "map": "Molten Boss Fractal", "agony": 148, "mistlock_instability": ["Boon Thieves", "Social Awkwardness"] },
      { "scale": 100, "map": "Captain Mai Trin Boss Fractal", "agony": 150, "mistlock_instability": ["Boon Thieves", "Social Awkwardness"] }
  ]
}
